In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
print(a[0])

[1 2 3 4]


In [5]:
a = np.array([[0., 0., 0.],[1., 1., 1.]])

In [6]:
a.shape

(2, 3)

In [7]:
a[1,2] = 100
print(a)

[[  0.   0.   0.]
 [  1.   1. 100.]]


In [8]:
a = np.array([1,2,3])

In [9]:
print(np.zeros(2))

[0. 0.]


In [10]:
print(np.ones(2))

[1. 1.]


In [11]:
%%time
a = np.zeros((10000,1000,1000))

CPU times: total: 0 ns
Wall time: 728 ms


In [12]:
%%time
del(a)
a = np.empty((10000,1000,1000))

CPU times: total: 0 ns
Wall time: 12 ms


In [13]:
np.arange(4)

array([0, 1, 2, 3])

In [14]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [15]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
x = np.ones(2, dtype=np.int64)

In [17]:
x.dtype

dtype('int64')

In [18]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [19]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [21]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
array_example = np.array([[[0, 1, 2, 3],
                        [4, 5, 6, 7]],

                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]],

                        [[0 ,1 ,2, 3],
                        [4, 5, 6, 7]]])

In [24]:
array_example.ndim

3

In [25]:
array_example.size

24

In [26]:
array_example.shape

(3, 2, 4)

In [27]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [28]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [29]:
??np.reshape

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [31]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [32]:
a2.squeeze()

array([1, 2, 3, 4, 5, 6])

In [33]:
data = np.array([1, 2, 3])

In [34]:
data[1]

2

In [35]:
data[0:2]

array([1, 2])

In [36]:
data[1:]

array([2, 3])

In [37]:
data[-2:]

array([2, 3])

In [38]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [39]:
print(a[a < 5])

[1 2 3 4]


In [40]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [41]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [42]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [43]:
ind = np.argwhere((a > 2) & (a < 11))
print(ind)

[[0 2]
 [0 3]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [2 0]
 [2 1]]


In [44]:
ind = np.where((a > 2) & (a < 11))
print(a[ind])

[ 3  4  5  6  7  8  9 10]


In [45]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [47]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [48]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [49]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [50]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a
b is a

True

In [51]:
def f(x):
    print(id(x))

f(a)
f(b)

2270482469712
2270482469712


In [52]:
c = a.view()
c is a

False

In [53]:
c.base is a            # c is a view of the data owned by a

True

In [54]:
c = c.reshape((2, 6)) # a's shape doesn't change

In [55]:
a.shape

(3, 4)

In [56]:
c[0, 4] = 1234         # a's data changes

In [57]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [58]:
d = a.copy()  # a new array object with new data is created


In [59]:
d is a


False

In [60]:
d.base is a  # d doesn't share anything with a


False

In [61]:
d[0, 0] = 9999


In [62]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [63]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [64]:
data - ones

array([0, 1])

In [65]:
data * data

array([1, 4])

In [66]:
data / data

array([1., 1.])

In [67]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [68]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [69]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=1)

array([2, 4])

In [70]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [71]:

a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])


In [72]:

unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [73]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [74]:
?? np.unique

In [75]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [76]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])